- name: Install zsh packages
  become: yes
  apt:
    name:
        - zsh
        - lolcat
        - figlet
        - direnv
- name: Clone Prezto
  git:
    repo: 'https://github.com/sorin-ionescu/prezto.git'
    dest: '/home/{{ ansible_user }}/.local/share/zprezto'
