- name: Install neovim
  become: yes
  apt:
    name:
        - neovim
- name: Create neovim config directory
  file: path={{ xdg_config_home }}/nvim/autoload state=directory
- name: Bootstrap vim.plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ xdg_config_home }}/nvim/autoload/'

