- name: Install fonts
  become: yes
  apt:
    name:
        - fonts-powerline
        - fonts-hack
- name: Create fonts directory
  file: path={{ xdg_data_home }}/fonts state=directory

- name: Fetch FontAwesome
  unarchive:
    src: https://github.com/FortAwesome/Font-Awesome/releases/download/5.12.1/fontawesome-free-5.12.1-desktop.zip
    dest: '{{ xdg_data_home }}/fonts/'
    remote_src: yes

- name: Update font cache
  command: fc-cache -f -v

